runtime: java21
instance_class: F2
service: api

env_variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql:///mislice?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=xx-1-2e007:us-central1:mislice-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "mislicepassword123"
  SPRING_PROFILES_ACTIVE: "prod"
  CORS_ORIGINS: "*"
  JWT_SECRET: "c2VjdXJlLXByb2R1Y3Rpb24tc2VjcmV0LWtleS1taXNsaWNlMjAyNg=="
  REDIS_HOST: "10.66.194.219"

vpc_access_connector:
  name: projects/xx-1-2e007/locations/us-central1/connectors/mislice-vpc
