-- ============================================================================
-- MiSlice seed V4 — marketplace demo data (GENERATED by scripts/generate_v4_seed.py)
-- Demo credentials all use password 'password' (BCrypt) — dev/demo only.
-- ============================================================================

-- ── Comparison chains ────────────────────────────────────────────────────────
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('39d89559-5366-5a3f-8267-6479edeea060', 'dominos', 'Domino''s', 'bg-blue-600', '{"Small": 8.99, "Medium": 12.99, "Large": 15.99, "Extra Large": 17.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 1.0, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 2.5, "Gluten Free Crust": 3.0}'::jsonb, 1.5, 4.99, 'STORE_DELIVERY', TRUE, TRUE, FALSE, FALSE, FALSE, '1.2 miles', 0, 'system');
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('3a8a6d7f-9b03-5e75-928a-87aaa32db375', 'papa-johns', 'Papa Johns', 'bg-green-700', '{"Small": 9.99, "Medium": 14.99, "Large": 17.99, "Extra Large": 19.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 1.5, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 3.0, "Gluten Free Crust": 3.0}'::jsonb, 1.75, 5.49, 'STORE_DELIVERY', TRUE, TRUE, TRUE, FALSE, FALSE, '2.5 miles', 1, 'system');
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('7bad92ca-a4ff-5dff-a605-2f11e4c2a262', 'pizza-hut', 'Pizza Hut', 'bg-red-600', '{"Small": 9.99, "Medium": 13.99, "Large": 16.99, "Extra Large": 18.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 1.0, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 2.0, "Gluten Free Crust": 2.5}'::jsonb, 1.25, 4.5, 'STORE_DELIVERY', TRUE, TRUE, TRUE, TRUE, TRUE, '1.8 miles', 2, 'system');
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('812a6953-6124-5bd5-a881-0506c571b178', 'jets-pizza', 'Jet''s Pizza', 'bg-red-700', '{"Small": 12.99, "Medium": 16.99, "Large": 20.99, "Extra Large": 24.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 0, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 0, "Gluten Free Crust": 2.5}'::jsonb, 2.0, 0, 'THIRD_PARTY', FALSE, TRUE, TRUE, TRUE, TRUE, '0.8 miles', 3, 'system');
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('dcdb4ca0-5150-5f62-860e-1220d0a500c4', 'marcos-pizza', 'Marco''s Pizza', 'bg-red-800', '{"Small": 11.99, "Medium": 14.99, "Large": 18.99, "Extra Large": 21.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 0, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 0, "Gluten Free Crust": 3.0}'::jsonb, 1.75, 0, 'THIRD_PARTY', FALSE, TRUE, TRUE, TRUE, TRUE, '3.2 miles', 4, 'system');
INSERT INTO chains (id, chain_key, name, color, base_prices, crust_premiums, topping_price, store_delivery_fee, default_delivery_type, supports_store_delivery, supports_pickup, supports_doordash, supports_ubereats, supports_grubhub, distance_label, sort_order, created_by)
VALUES ('0fc03d54-84a1-5fd3-8057-c1b996585555', 'buntys-pizza', 'Bunty''s Pizza', 'bg-orange-600', '{"Small": 2.49, "Medium": 3.49, "Large": 14.49, "Extra Large": 16.99}'::jsonb, '{"Hand Tossed": 0, "Handmade Pan": 1.0, "Crunchy Thin Crust": 0, "Brooklyn Style": 0, "New York Style": 0, "Parmesan Stuffed Crust": 2.5, "Gluten Free Crust": 2.5}'::jsonb, 0.29, 0.49, 'STORE_DELIVERY', TRUE, TRUE, TRUE, TRUE, FALSE, '0.4 miles', 5, 'system');

INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('86ea91da-d09a-5d48-8dc6-742cb8716fe6', '39d89559-5366-5a3f-8267-6479edeea060', 'Alex', 4, 'Fast delivery, good crust.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('8453eacb-c723-55ad-8101-592494f387dd', '39d89559-5366-5a3f-8267-6479edeea060', 'Jamie', 5, 'Always my go-to!', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('100daf56-fd6b-5541-90da-38c45cfda5c6', '3a8a6d7f-9b03-5e75-928a-87aaa32db375', 'Chris', 4, 'Love the garlic sauce.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('5edeec28-646f-5f73-a3a8-83f2fb098a90', '7bad92ca-a4ff-5dff-a605-2f11e4c2a262', 'Sam', 3, 'Pizza was okay, delivery time a bit long.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('ce7242ad-56f8-5787-9d04-2c6253bd18ab', '7bad92ca-a4ff-5dff-a605-2f11e4c2a262', 'Taylor', 4, 'Stuffed crust is legendary.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('e70e301f-d8a4-55d7-9a4e-18c05488b3ff', '812a6953-6124-5bd5-a881-0506c571b178', 'Jordan', 5, 'Detroit style deep dish is unbeatable!', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('490f1a58-c986-51b2-942a-c313d54ed231', '0fc03d54-84a1-5fd3-8057-c1b996585555', 'Ravi', 5, 'Best local pizza in Michigan, hands down!', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('0289e2a6-4380-5527-98bb-ab653742631d', '0fc03d54-84a1-5fd3-8057-c1b996585555', 'Priya', 5, 'Lamb topping is amazing, never going anywhere else.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('5ec7972b-a8b3-50e0-b472-dc766309f628', '0fc03d54-84a1-5fd3-8057-c1b996585555', 'Mike', 4, 'Great value, fast delivery and fresh ingredients.', 'system');
INSERT INTO chain_reviews (id, chain_id, author_name, rating, comment, created_by)
VALUES ('7ac4b1ab-d8af-50f1-beaf-846e076e92d9', '0fc03d54-84a1-5fd3-8057-c1b996585555', 'Sara', 5, 'The garlic butter drizzle is unreal. 10/10!', 'system');

-- ── Demo users ───────────────────────────────────────────────────────────────
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'sathyasaisskr@gmail.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Sathya', '313-555-9901', 'ACTIVE', TRUE, ARRAY['Pepperoni', 'Chicken', 'Lamb'], NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'CUSTOMER');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', 'demo@mislice.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Alex Johnson', '734-555-8802', 'ACTIVE', TRUE, ARRAY['Chicken', 'Italian Sausage'], NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', 'CUSTOMER');

INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('6490766e-fd89-5604-b662-a24dd6641852', 'owner@motorcityslice.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Motor City Slice Owner', '734-555-0202', 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('6490766e-fd89-5604-b662-a24dd6641852', 'RESTAURANT_OWNER');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('29f1e635-a83c-5389-894b-472cfa41255a', 'owner@greatlakespies.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Great Lakes Pies Owner', '616-555-0303', 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('29f1e635-a83c-5389-894b-472cfa41255a', 'RESTAURANT_OWNER');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('4d5a6326-a9ab-55eb-aeee-ba1efb6a631e', 'owner@rambospizza.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Rambo''s Pizza Owner', '313-555-7777', 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('4d5a6326-a9ab-55eb-aeee-ba1efb6a631e', 'RESTAURANT_OWNER');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('8d7ad7ee-007c-51be-afa8-905c6e82e78f', 'owner@zumbospizza.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Zumbo''s Pizza Owner', '313-555-9999', 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('8d7ad7ee-007c-51be-afa8-905c6e82e78f', 'RESTAURANT_OWNER');

INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('b2d486d5-6b62-5c8d-92a8-d384f0001c05', 'manager@zumbo.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Zumbo Manager', NULL, 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('b2d486d5-6b62-5c8d-92a8-d384f0001c05', 'RESTAURANT_STAFF');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('b482b9b7-d0ce-5da1-bc4c-7dfce93672cc', 'kitchen@zumbo.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Zumbo Kitchen', NULL, 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('b482b9b7-d0ce-5da1-bc4c-7dfce93672cc', 'RESTAURANT_STAFF');
INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('8795fc6c-91bb-539b-9278-d6fee918f5ab', 'cashier@zumbo.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Zumbo Cashier', NULL, 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('8795fc6c-91bb-539b-9278-d6fee918f5ab', 'RESTAURANT_STAFF');

-- ── Marketplace restaurants ─────────────────────────────────────────────────
UPDATE restaurants SET delivery_fee = 2.99, delivery_radius_miles = 5, minimum_order = 12.0, average_eta_minutes = 28, emoji = '🍕', category = 'LOCAL', price_range = '$$', neighborhood = 'Downtown Detroit', trend_score = 88, is_featured = TRUE, is_new = FALSE, tags = ARRAY['halal'], badges = ARRAY['Top Rated', 'Local'], popular_items = ARRAY['Detroit Deep Dish', 'Pepperoni Supreme'], delivery_partners = ARRAY['store', 'pickup', 'doordash'], description = 'Detroit-style deep dish with crispy edges, fresh toppings, and bold flavors since 2018.', latitude = 42.3314, longitude = -83.0458, address_line = '1234 Woodward Ave, Detroit, MI 48201', brand_color = '#E63946'
WHERE id = '00000000-0000-0000-0000-0000000000c1';
INSERT INTO restaurants (id, owner_id, name, slug, description, phone, address_line, city, state, postal_code, latitude, longitude, brand_color, rating_avg, rating_count, accepting_orders, is_approved, application_status, is_setup_complete, delivery_fee, delivery_radius_miles, minimum_order, average_eta_minutes, emoji, category, price_range, neighborhood, trend_score, is_featured, is_new, tags, badges, popular_items, delivery_partners, created_by)
VALUES ('1795704f-8414-5907-904c-9bb7b6c3c818', '6490766e-fd89-5604-b662-a24dd6641852', 'Motor City Slice', 'motor-city-slice', 'New York-style hand-tossed pies made with locally sourced Michigan ingredients.', '734-555-0202', '502 E Liberty St, Ann Arbor, MI 48104', 'Ann Arbor', 'MI', '48104', 42.2808, -83.743, '#F4A261', 4.5, 198, TRUE, TRUE, 'APPROVED', TRUE, 1.99, 4, 10.0, 35, '🏎️', 'LOCAL', '$$', 'Ann Arbor', 74, FALSE, FALSE, ARRAY['vegetarian'], ARRAY['Free Delivery'], ARRAY['Motor City Special', 'Veggie Slice'], ARRAY['store', 'pickup', 'ubereats'], 'system');
INSERT INTO restaurants (id, owner_id, name, slug, description, phone, address_line, city, state, postal_code, latitude, longitude, brand_color, rating_avg, rating_count, accepting_orders, is_approved, application_status, is_setup_complete, delivery_fee, delivery_radius_miles, minimum_order, average_eta_minutes, emoji, category, price_range, neighborhood, trend_score, is_featured, is_new, tags, badges, popular_items, delivery_partners, created_by)
VALUES ('133a0c7e-1d95-5009-a1c7-c7389a9f57b8', '29f1e635-a83c-5389-894b-472cfa41255a', 'Great Lakes Pies', 'great-lakes-pies', 'West Michigan''s favorite thin crust spot — crispy, saucy, and loaded with premium toppings.', '616-555-0303', '88 Monroe Center St NW, Grand Rapids, MI 49503', 'Grand Rapids', 'MI', '49503', 42.9634, -85.6681, '#2A9D8F', 4.6, 441, TRUE, TRUE, 'APPROVED', TRUE, 3.49, 6, 14.0, 32, '🌊', 'ARTISAN', '$$$', 'Grand Rapids', 81, TRUE, FALSE, ARRAY['vegetarian', 'gluten-free'], ARRAY['Top Rated'], ARRAY['Lake Effect Supreme', 'Artisan Margherita'], ARRAY['store', 'pickup', 'doordash', 'grubhub'], 'system');
INSERT INTO restaurants (id, owner_id, name, slug, description, phone, address_line, city, state, postal_code, latitude, longitude, brand_color, rating_avg, rating_count, accepting_orders, is_approved, application_status, is_setup_complete, delivery_fee, delivery_radius_miles, minimum_order, average_eta_minutes, emoji, category, price_range, neighborhood, trend_score, is_featured, is_new, tags, badges, popular_items, delivery_partners, created_by)
VALUES ('cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', '4d5a6326-a9ab-55eb-aeee-ba1efb6a631e', 'Rambo''s Pizza', 'rambos-pizza', 'Action-packed flavor! The best pizzas in town, baked to perfection.', '313-555-7777', '777 Action Way, Detroit, MI 48201', 'Detroit', 'MI', '48201', 42.3314, -83.0458, '#FF3B30', 4.8, 120, TRUE, TRUE, 'APPROVED', TRUE, 1.99, 5, 10.0, 20, '💪', 'LOCAL', '$', 'Detroit — Mexicantown', 65, FALSE, TRUE, ARRAY['spicy'], ARRAY['New'], ARRAY['Rambo Firehouse'], ARRAY['store', 'pickup'], 'system');
INSERT INTO restaurants (id, owner_id, name, slug, description, phone, address_line, city, state, postal_code, latitude, longitude, brand_color, rating_avg, rating_count, accepting_orders, is_approved, application_status, is_setup_complete, delivery_fee, delivery_radius_miles, minimum_order, average_eta_minutes, emoji, category, price_range, neighborhood, trend_score, is_featured, is_new, tags, badges, popular_items, delivery_partners, created_by)
VALUES ('ed958015-25f3-5f80-a4db-0fae863238ec', '8d7ad7ee-007c-51be-afa8-905c6e82e78f', 'Zumbo''s Pizza', 'zumbos-pizza', 'Detroit''s hidden gem for artisanal pizzas, including our famous Chicken Parmesan Pizza.', '313-555-9999', '999 Zumbo Way, Detroit, MI 48201', 'Detroit', 'MI', '48201', 42.3314, -83.0458, '#E63946', 4.9, 85, TRUE, TRUE, 'APPROVED', TRUE, 2.49, 5, 12.0, 25, '🎪', 'PREMIUM', '$$$', 'Detroit — Midtown', 93, TRUE, FALSE, ARRAY['vegetarian'], ARRAY['#1 in Detroit'], ARRAY['Chicken Parmesan Pizza'], ARRAY['store', 'pickup', 'doordash', 'ubereats'], 'system');

INSERT INTO users (id, email, password_hash, full_name, phone, account_status, email_verified, meat_prefs, avatar_url, created_by)
VALUES ('747d56d2-f7d9-528e-b273-116ec36c2f7f', 'owner@crustandcraft.com', '$2y$10$psLnGc7w/JKusJm2GtVAH.osm/AE3Zj3ozcSTZfvsPI2x8xnWH6cy', 'Crust & Craft Owner', '313-555-0177', 'ACTIVE', TRUE, NULL, NULL, 'system');
INSERT INTO user_roles (user_id, role) VALUES ('747d56d2-f7d9-528e-b273-116ec36c2f7f', 'RESTAURANT_OWNER');
INSERT INTO restaurants (id, owner_id, name, slug, description, phone, address_line, city, state, accepting_orders, is_approved, application_status, submitted_at, is_setup_complete, emoji, category, price_range, neighborhood, delivery_partners, created_by)
VALUES ('14cd8036-5404-53dc-af27-0bd8c31efdfe', '747d56d2-f7d9-528e-b273-116ec36c2f7f', 'Crust & Craft', 'crust-and-craft', 'Wood-fired artisan pies with locally sourced ingredients.', '313-555-0177', '88 Bagley St, Detroit, MI 48226', 'Detroit', 'MI', FALSE, FALSE, 'SUBMITTED', now() - interval '2 days', TRUE, '🔥', 'ARTISAN', '$$$', 'Corktown', ARRAY['store','pickup'], 'system');

INSERT INTO restaurant_members (id, restaurant_id, user_id, member_role, created_by)
VALUES ('080373ac-c2e3-5a17-aadb-44639d75c031', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'b2d486d5-6b62-5c8d-92a8-d384f0001c05', 'MANAGER', 'system');
INSERT INTO restaurant_members (id, restaurant_id, user_id, member_role, created_by)
VALUES ('26c2a8b9-0962-507d-8c46-18f84c073911', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'b482b9b7-d0ce-5da1-bc4c-7dfce93672cc', 'KITCHEN_STAFF', 'system');
INSERT INTO restaurant_members (id, restaurant_id, user_id, member_role, created_by)
VALUES ('40e30847-ed2d-59b7-ba1e-ecbd08d8f15c', 'ed958015-25f3-5f80-a4db-0fae863238ec', '8795fc6c-91bb-539b-9278-d6fee918f5ab', 'CASHIER', 'system');

-- ── Store hours (11:00–22:00 daily) ─────────────────────────────────────────
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('28e0f368-c90e-555b-97ef-c5b7a1f133d7', '1795704f-8414-5907-904c-9bb7b6c3c818', 0, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('ccb39364-1b7e-505a-a6fc-e01cad564520', '1795704f-8414-5907-904c-9bb7b6c3c818', 1, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('c788c7c2-3886-5a48-9017-4836fb895996', '1795704f-8414-5907-904c-9bb7b6c3c818', 2, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('914c320b-3614-5717-a3c7-7b3b2d09f873', '1795704f-8414-5907-904c-9bb7b6c3c818', 3, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('6fbcc9ed-b289-54e3-8747-849697a90ce1', '1795704f-8414-5907-904c-9bb7b6c3c818', 4, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('3506a844-5ed6-53c2-9682-c3e65d7c8b6d', '1795704f-8414-5907-904c-9bb7b6c3c818', 5, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('ba7e0adb-022e-5e39-8158-c26f36b117f6', '1795704f-8414-5907-904c-9bb7b6c3c818', 6, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('9a4af439-3043-508c-8f1c-621fc8a8d169', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 0, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('5806ee6b-044c-5970-988c-3be3668f401d', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 1, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('1cb8c5ea-1940-5ab7-889c-0715718c48fd', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 2, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('619146f2-1196-5366-ba69-d5f454e1f801', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 3, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('6d847582-297f-566a-837a-a53efd50f289', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 4, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('e1aa3323-df22-5873-a8f5-a63c1fda2bfa', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 5, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('8fed913d-849c-5329-8aaf-b2d7bcec7fa1', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 6, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('4063ca51-3f9a-5012-9db2-15baf3ae1085', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 0, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('b5ca8a20-e2e3-571b-b94e-e292531b3be6', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 1, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('4aca9a01-1c23-53f0-863d-baca9ac0a504', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 2, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('ec284e4e-2da1-50a7-a614-6c1a8ae29c06', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 3, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('4edf3616-4a18-570f-b80b-00f3681a272a', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 4, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('6500e3d6-3dbb-56df-8251-22a43bee7291', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 5, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('d9c5179a-8b5c-5e8e-95cf-cf730d43bb56', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 6, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('d405e1f4-14ab-53f1-ab81-c4d69e628850', 'ed958015-25f3-5f80-a4db-0fae863238ec', 0, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('9e19fd7f-1fe9-5b0b-ade4-c05ba2687d2c', 'ed958015-25f3-5f80-a4db-0fae863238ec', 1, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('fd9e9560-963f-5ec8-a22c-3d7d1b8ecdf8', 'ed958015-25f3-5f80-a4db-0fae863238ec', 2, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('41280b60-ea17-5ba9-b954-f00d24807ad7', 'ed958015-25f3-5f80-a4db-0fae863238ec', 3, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('5064b93a-0856-54bb-9c22-970f2527a134', 'ed958015-25f3-5f80-a4db-0fae863238ec', 4, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('241e7962-036c-578b-aabb-f518af6e01a3', 'ed958015-25f3-5f80-a4db-0fae863238ec', 5, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('6217e5e8-e113-5d59-8c9f-bff8f9c86b9e', 'ed958015-25f3-5f80-a4db-0fae863238ec', 6, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('2b46a9ab-785d-5fd5-a7c8-01ad0321d596', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 0, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('16ee5264-70a1-52f6-a7d6-a0b491699bc4', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 1, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('5d0befab-094e-55e1-862e-642db2a3c8b4', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 2, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('5d093f39-0b33-512b-8968-a0ddd8c53823', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 3, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('f38b7a1c-ff47-55cf-866a-87f006994e15', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 4, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('fde7ac31-62cc-5180-933d-e8fa2e17a369', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 5, '11:00', '22:00', FALSE, 'system');
INSERT INTO restaurant_hours (id, restaurant_id, day_of_week, open_time, close_time, closed, created_by) VALUES ('2d19b921-8f97-5be8-84ea-fd4324f80480', '14cd8036-5404-53dc-af27-0bd8c31efdfe', 6, '11:00', '22:00', FALSE, 'system');

-- ── Menus (from mock catalog: base_pizza→sizes, crust_upgrade→crusts,
--    meat/veggie/cheese/drizzle→toppings, specialty→menu items) ─────────────
UPDATE pizza_sizes SET is_deleted = TRUE WHERE restaurant_id = '00000000-0000-0000-0000-0000000000c1';
UPDATE crust_types SET is_deleted = TRUE WHERE restaurant_id = '00000000-0000-0000-0000-0000000000c1';
UPDATE toppings    SET is_deleted = TRUE WHERE restaurant_id = '00000000-0000-0000-0000-0000000000c1';

INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('6cda00a5-c3ca-531c-a66f-2c4c6444683a', '00000000-0000-0000-0000-0000000000c1', 'Build Your Own Pizza', 'Start with our hand-made dough and pick every layer yourself.', 9.99, 'PIZZA', ARRAY['base'], TRUE, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('829bfd3f-7cd1-5c72-8887-f3115d51a1a7', '00000000-0000-0000-0000-0000000000c1', 'Small', 0.0, 0, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('e5685fa2-e788-5515-824c-fd90044c0724', '00000000-0000-0000-0000-0000000000c1', 'Medium', 3.0, 1, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('de02e295-9334-5590-ac54-16ba0c00faad', '00000000-0000-0000-0000-0000000000c1', 'Large', 6.0, 2, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('f4c72a86-505a-5d5e-95d2-8f4359c60b02', '00000000-0000-0000-0000-0000000000c1', 'Extra Large', 9.0, 3, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('ba9b2297-326e-5550-aa67-1aebdebd53b6', '00000000-0000-0000-0000-0000000000c1', 'Hand Tossed', 0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('c2276149-4dfc-50cc-ab80-ae05d074bf33', '00000000-0000-0000-0000-0000000000c1', 'Crunchy Thin Crust', 0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('aa72aff4-ef31-5df8-a6cf-c6270389146c', '00000000-0000-0000-0000-0000000000c1', 'Pepperoni', 'MEAT', 1.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('965103ab-c0b6-5381-9f20-fbd588ec702b', '00000000-0000-0000-0000-0000000000c1', 'Grilled Chicken', 'MEAT', 1.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('3a20e7d0-df7f-533a-93bd-080948c8d017', '00000000-0000-0000-0000-0000000000c1', 'Beef', 'MEAT', 1.79, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('913d6d19-b242-5ab3-94ec-1b01b8d249f6', '00000000-0000-0000-0000-0000000000c1', 'Italian Sausage', 'MEAT', 1.69, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('42ba7d04-fd32-5d38-8b1a-1bcf3f012f10', '00000000-0000-0000-0000-0000000000c1', 'Lamb', 'MEAT', 2.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('c7bedd26-7aa6-5f65-813a-3b1fb34d7fe3', '00000000-0000-0000-0000-0000000000c1', 'Anchovies', 'MEAT', 1.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('8a8f462a-d6ad-58c5-a4fa-744d59f9e2fe', '00000000-0000-0000-0000-0000000000c1', 'Mushrooms', 'VEGGIE', 1.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('d97b4e52-433e-5aae-9c88-e084be99e916', '00000000-0000-0000-0000-0000000000c1', 'Onions', 'VEGGIE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('62c10e73-e376-5baf-8ed2-eac084cd615f', '00000000-0000-0000-0000-0000000000c1', 'Bell Peppers', 'VEGGIE', 1.09, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('042f0ece-8614-576c-be35-6379fee0e2cc', '00000000-0000-0000-0000-0000000000c1', 'Black Olives', 'VEGGIE', 1.09, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('1009de12-cd24-5eac-86c4-b86f92aff1e9', '00000000-0000-0000-0000-0000000000c1', 'Spinach', 'VEGGIE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('03b43607-816a-594e-8964-d74ca66e3dbb', '00000000-0000-0000-0000-0000000000c1', 'Extra Cheese', 'CHEESE', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('5f06e86c-a961-5ad0-a8de-1baf2379a7d5', '00000000-0000-0000-0000-0000000000c1', 'Feta', 'CHEESE', 1.79, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('8bd8303e-14b0-52dc-81e0-3b484f664835', '00000000-0000-0000-0000-0000000000c1', 'Cheddar', 'CHEESE', 1.29, TRUE, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('f91f0a76-7efe-51a8-a4d7-08f64d0b0c1b', '00000000-0000-0000-0000-0000000000c1', 'Parmesan Stuffed Crust', 3.0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('e2ccfbd6-f75e-5ecb-a85e-70a87a1c8b23', '00000000-0000-0000-0000-0000000000c1', 'Gluten Free Crust', 2.5, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('be61c40c-6a07-5c81-ae9d-e602fd33c45f', '00000000-0000-0000-0000-0000000000c1', 'Garlic Butter Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('c7e10c1e-cb79-524e-a522-b12f73888dd1', '00000000-0000-0000-0000-0000000000c1', 'Ranch Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('4868c81e-422c-5276-8917-c9e188b6e3eb', '00000000-0000-0000-0000-0000000000c1', 'Buffalo Drizzle', 'SAUCE', 0.49, TRUE, 'system');

INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('6c576013-8528-5fb6-a78b-bdd1167aa1cd', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Build Your Own Pizza', 'Start with our hand-made dough and pick every layer yourself.', 8.99, 'PIZZA', ARRAY['base'], TRUE, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('6cefdd2c-ffe4-5a82-a5b8-4826472ac057', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Small', 0.0, 0, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('aa79f4bb-b7ac-5a73-b146-25a99ee021a3', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Medium', 3.0, 1, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('b6703418-2c51-5f63-9054-b20ab6fe842e', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Large', 6.0, 2, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('10046d69-c75c-5dff-8ee0-cd36647e4f66', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Extra Large', 9.0, 3, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('f16dc9af-41fd-5def-a81b-0d8084f0e7d8', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Hand Tossed', 0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('7d9eef52-258e-566b-a2e4-9749d28b8951', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Crunchy Thin Crust', 0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('7bb2f81c-89ad-5535-b62d-08a968f6397e', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Pepperoni', 'MEAT', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('5d14cace-617f-5007-be8c-64b9b8591a1f', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Grilled Chicken', 'MEAT', 1.69, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('698e6032-b6cc-5f4c-8dfb-311a89a903b3', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Beef', 'MEAT', 1.59, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('e28c5f30-84aa-5fb3-aab0-6df5002bf40d', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Italian Sausage', 'MEAT', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('04747829-037d-5a2d-bc65-43b88fb701df', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Lamb', 'MEAT', 1.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('7903d82e-fdcd-5edc-8112-ab00210e3b02', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Anchovies', 'MEAT', 1.69, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('0428fce6-dcd6-5a8a-9530-190c5d28b7f4', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Mushrooms', 'VEGGIE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('a06f8ad1-fa0e-5cc0-b149-5d17cce6d143', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Onions', 'VEGGIE', 0.79, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('e3663e3c-85b8-5c6f-acd3-835511043be8', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Bell Peppers', 'VEGGIE', 0.89, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('46150758-b4be-590a-8be9-a4bc8c0df690', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Black Olives', 'VEGGIE', 0.89, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('b50293cb-4b25-5c9a-98c5-4e5124c97000', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Spinach', 'VEGGIE', 0.89, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('b41ba1da-ea05-58f5-9a15-d149f411adae', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Extra Cheese', 'CHEESE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('ecdcebeb-2ebd-5ebc-939b-eabaecca0d66', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Feta', 'CHEESE', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('15027458-1c3c-59d4-8e96-be24d5531a55', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Cheddar', 'CHEESE', 1.09, TRUE, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('fe8c27ce-b436-537d-baba-2ff48dbb3296', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Parmesan Stuffed Crust', 2.5, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('625e4df1-8e28-5726-a0b4-461c701dcf85', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Gluten Free Crust', 2.0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('c8b52c49-5a01-5b37-a5cf-72b8069a9581', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Garlic Butter Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('816e9c43-8489-5b4b-a090-d1364abe83e5', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Ranch Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('0fb74b31-26a0-5146-9210-61d385ec1092', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Balsamic Drizzle', 'SAUCE', 0.49, TRUE, 'system');

INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('3c6d58db-37c0-5830-aabf-ebf7b832c68b', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Build Your Own Pizza', 'Start with our hand-made dough and pick every layer yourself.', 9.49, 'PIZZA', ARRAY['base'], TRUE, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('f1156cc6-8c7c-55ab-aae9-45be5887657b', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Small', 0.0, 0, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('10e0e528-a9c5-5c39-85c9-088c37295a7f', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Medium', 3.0, 1, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('12f2bde4-fca1-5138-9370-8d5dd37a393d', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Large', 6.0, 2, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('067f2506-0566-5ca0-9600-69a0a72c2aaf', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Extra Large', 9.0, 3, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('b12e3df5-611b-5cb6-adb5-1a238ce71df8', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Hand Tossed', 0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('62561963-edac-5772-8ba8-41118b1f3feb', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Crunchy Thin Crust', 0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('0d0ac604-e3c3-5126-8edd-30bf3c81d9fa', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Pepperoni', 'MEAT', 1.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('71e4a8ad-8456-597b-8a89-64d8f8887450', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Grilled Chicken', 'MEAT', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('6a37714f-907f-5f27-aafc-da972c63f57b', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Beef', 'MEAT', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('6880073f-f1b0-576e-8bae-deb25998302f', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Italian Sausage', 'MEAT', 1.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('256ee6a6-efb2-5201-8522-248ef8978db5', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Lamb', 'MEAT', 1.79, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('98429fc8-1e07-5693-aa47-75f130e32acf', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Anchovies', 'MEAT', 1.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('dfb3d2a7-c66b-51fc-b0ef-cb0d0d754e75', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Mushrooms', 'VEGGIE', 1.09, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('ddebef5e-87bb-5ad1-a684-aec2dd54be4e', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Onions', 'VEGGIE', 0.89, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('8ec38a74-1099-5248-889d-883a8d643925', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Bell Peppers', 'VEGGIE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('b8280d3b-0a5d-57af-a229-9479ad1ee904', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Black Olives', 'VEGGIE', 1.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('55d3e68f-dfe4-56a0-a990-f4c8a057f8e9', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Spinach', 'VEGGIE', 0.99, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('7bb77b51-6b7c-5843-9422-f983e24d5d78', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Extra Cheese', 'CHEESE', 1.29, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('0b6ed56d-4ae4-517a-b798-b507c37d460d', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Feta', 'CHEESE', 1.69, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('54966f81-8ce7-5ba7-a347-00114a1e15ad', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Cheddar', 'CHEESE', 1.19, TRUE, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('d331b1df-d029-51f3-8153-e216cf637b6a', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Parmesan Stuffed Crust', 2.99, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('c13ad30d-b50e-595c-9636-54a194ba7ea9', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Gluten Free Crust', 3.0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('765ba4b0-5d58-5c12-97fa-a489b87756cc', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Garlic Butter Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('136e6018-b7c4-5f41-98be-7be75a83a214', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Buffalo Drizzle', 'SAUCE', 0.49, TRUE, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('7d02ee44-c8e7-5f3c-a63d-0f84c7ea48ed', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Balsamic Drizzle', 'SAUCE', 0.49, TRUE, 'system');

INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('836c72ea-8600-5304-9481-d30a513c0d59', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Build Your Own Pizza', 'Start with our hand-made dough and pick every layer yourself.', 9.99, 'PIZZA', ARRAY['base'], TRUE, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('f11c8319-b03b-563c-89ce-695b2ca2907d', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Small', 0.0, 0, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('f86415a2-5769-5fb2-9374-8b8281b4f86b', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Medium', 3.0, 1, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('0b951467-ff7f-581d-9623-37e21a19a9f4', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Large', 6.0, 2, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('4465c28e-4d09-51a4-9525-562aae7f6ca8', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Extra Large', 9.0, 3, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('e26687e5-efdc-5cf2-9522-ec6c69feb623', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Hand Tossed', 0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('b1e80063-1e0d-56e5-9cb3-6bed26ea5dbc', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Crunchy Thin Crust', 0, 'system');
INSERT INTO toppings (id, restaurant_id, name, category, price, available, created_by) VALUES ('565c87a6-e444-5741-8a8b-238307f5b0cf', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', 'Pepperoni', 'MEAT', 1.99, TRUE, 'system');

INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('ecce0efe-3e94-568e-abfa-c9504fe71538', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Build Your Own Pizza', 'Start with our hand-made dough and pick every layer yourself.', 9.99, 'PIZZA', ARRAY['base'], TRUE, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('86a618c1-aebe-569f-89d7-6fbb282cb634', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Small', 0.0, 0, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('3fa4d9b9-e784-5057-b36c-68a4c0ae166d', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Medium', 3.0, 1, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('c198659a-619a-5408-9eed-c647d8662935', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Large', 6.0, 2, 'system');
INSERT INTO pizza_sizes (id, restaurant_id, name, price_delta, sort_order, created_by) VALUES ('2d25be68-6acc-5caf-a393-a6a47cf71489', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Extra Large', 9.0, 3, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('1c15a6de-ab78-5cb1-adf0-f19861061f6b', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Hand Tossed', 0, 'system');
INSERT INTO crust_types (id, restaurant_id, name, price_delta, created_by) VALUES ('e5a7a586-574b-560e-9e43-66d872be6909', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Crunchy Thin Crust', 0, 'system');
INSERT INTO menu_items (id, restaurant_id, name, description, base_price, item_type, tags, available, created_by)
VALUES ('23e2726c-0d35-5249-870a-b05e1a3d58c7', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'Chicken Parmesan Pizza', 'Crispy chicken, rich marinara, loaded with mozzarella and grated parmesan cheese.', 18.99, 'PIZZA', ARRAY['popular', 'specialty'], TRUE, 'system');

-- ── Deals ────────────────────────────────────────────────────────────────────
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('de035456-918e-532f-9bd0-a1330bf9543b', '00000000-0000-0000-0000-0000000000c1', '2 Large Pizzas for $26', 'Any 2 large pizzas with up to 3 toppings each. Mix and match!', 31.98, 26.0, 'store-delivery', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('a82cba9f-e1a5-5cb0-8b2d-5ecbef0d5f0a', '00000000-0000-0000-0000-0000000000c1', 'Lunch Special — Medium + Drink $13', 'Any medium pizza with one topping and a fountain drink. Mon–Fri 11am–3pm.', 16.49, 13.0, 'pickup', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('9a11b156-0d71-5886-a00d-031a1a07f506', '00000000-0000-0000-0000-0000000000c1', 'Free Delivery Fridays', 'Every Friday — free store delivery on orders over $20.', 2.99, 0.0, 'store-delivery', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('0ff93a02-391f-5d35-bcf6-ae169556ac0b', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Student Deal — Large Pizza $12', 'Show your Michigan ID and get any large pizza for $12. Any toppings.', 14.99, 12.0, 'pickup', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('5b3bb611-4dd6-5f65-8984-7e5d328fae17', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Family Bundle — XL + Sides for $22', 'XL cheese pizza plus garlic bread and 2-liter soda.', 28.47, 22.0, 'store-delivery', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('0aa30ebb-2845-582f-8c60-582b0c476d41', '1795704f-8414-5907-904c-9bb7b6c3c818', 'Game Day Special — 3 Mediums $30', '3 medium pizzas, any toppings. Perfect for game night.', 35.97, 30.0, 'third-party', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('23a9b57e-f095-5fd2-8bf4-923ea8746b51', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Tuesday BOGO — Buy 1 Large, Get 1 Half Off', 'Every Tuesday — buy any large, get a second large at 50% off.', 30.98, 23.24, 'store-delivery', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('7600ab16-2338-51e8-a84a-02d8f607e3f3', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Pickup Saver — 20% Off Any Order', 'Order for pickup and save 20% on your entire order automatically.', 20.0, 16.0, 'pickup', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('eabbf784-934d-58e2-8800-9228ae2db00b', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'Gluten Free Friday — GF Crust Free', 'Every Friday the gluten free crust upgrade is on us.', 3.0, 0.0, 'store-delivery', TRUE, 'system');
INSERT INTO deals (id, restaurant_id, title, description, original_price, discounted_price, delivery_type, active, created_by)
VALUES ('ac35c628-337d-523f-8b46-63725f37595f', 'cc3c8da8-6b37-5b5d-9c6b-212964f11ff6', '4 Pizzas for $3', 'Action-packed flavor! Get 4 large pizzas with your choice of toppings for just $3.', 60.0, 3.0, 'pickup', TRUE, 'system');

-- ── Provider coupons used by the compare engine ─────────────────────────────
INSERT INTO coupons (id, code, description, discount_type, discount_value, provider, active, created_by)
VALUES ('a5b2f894-c738-5799-a1ec-31504f84a0ee', 'DASH10', '10% off delivery', 'PERCENT', 10, 'doordash', TRUE, 'system');
INSERT INTO coupons (id, code, description, discount_type, discount_value, provider, active, created_by)
VALUES ('17b3ee4b-4acc-5b02-ab86-f863a9d64ff6', 'SAVE5', 'Save $5 on orders', 'FIXED', 5, 'ubereats', TRUE, 'system');
INSERT INTO coupons (id, code, description, discount_type, discount_value, provider, active, created_by)
VALUES ('abd35a17-b65c-5d21-9dd1-0d89a6361bc9', 'FREEDEL', 'Free delivery today', 'FREE_DELIVERY', 0, 'store', TRUE, 'system');
UPDATE coupons SET provider = 'grubhub' WHERE code = 'GRUB7';

-- ── Demo customer favorites / loyalty / notifications ───────────────────────
INSERT INTO favorite_restaurants (id, user_id, restaurant_id, created_by) VALUES ('3be20ff2-ea29-5a2b-982d-c1e9f1057708', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', '00000000-0000-0000-0000-0000000000c1', 'system');
INSERT INTO favorite_restaurants (id, user_id, restaurant_id, created_by) VALUES ('7017fc1f-e55a-5a64-82bc-e0215623d363', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', '133a0c7e-1d95-5009-a1c7-c7389a9f57b8', 'system');
INSERT INTO favorite_configs (id, user_id, name, config, created_by)
VALUES ('b6aad163-2f35-59de-8406-b90a81b143f5', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'My Signature Pepperoni', '{"size": "Large", "crust": "Hand Tossed", "crustFlavor": "", "sauce": "Robust Inspired Tomato Sauce", "sauceAmount": "Normal", "cheeseAmount": "Extra", "cheese": ["Mozzarella"], "meats": ["Pepperoni"], "veggies": ["Mushrooms", "Bell Peppers"], "extras": [], "drizzles": ["Garlic Butter"], "toppingPlacements": {"Pepperoni": "whole", "Mushrooms": "whole"}, "toppingAmounts": {"Pepperoni": "Extra", "Mushrooms": "Moderate"}, "bakePreference": "Well Done", "cutStyle": "Pie Cut", "specialInstructions": "Extra crispy crust please", "quantity": 1}'::jsonb, 'system');
INSERT INTO favorite_restaurants (id, user_id, restaurant_id, created_by) VALUES ('a4ed8734-0fe2-53bf-928a-534c7b7982ff', 'b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', '1795704f-8414-5907-904c-9bb7b6c3c818', 'system');
INSERT INTO favorite_configs (id, user_id, name, config, created_by)
VALUES ('3c4bb449-8a25-54a9-8de7-c2e442b27f63', 'b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', 'BBQ Chicken Special', '{"size": "Medium", "crust": "Brooklyn Style", "crustFlavor": "", "sauce": "BBQ Sauce", "sauceAmount": "Extra", "cheeseAmount": "Normal", "cheese": ["Mozzarella", "Cheddar"], "meats": ["Chicken"], "veggies": ["Onions", "Spinach"], "extras": [], "drizzles": ["Ranch Drizzle"], "toppingPlacements": {"Chicken": "whole", "Onions": "whole"}, "toppingAmounts": {"Chicken": "Extra", "Onions": "Light"}, "bakePreference": "Normal Bake", "cutStyle": "Square Cut", "specialInstructions": "", "quantity": 2}'::jsonb, 'system');

INSERT INTO loyalty_accounts (id, user_id, points, lifetime_points, referral_code, created_by)
VALUES ('416ba529-3bc5-53cd-9076-c50476f1be81', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 1240, 1240, 'MISLICE-SATHYA', 'system');
INSERT INTO loyalty_accounts (id, user_id, points, lifetime_points, referral_code, created_by)
VALUES ('a25848a5-f9ea-5d45-a1b5-18e07ecee156', 'b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', 320, 320, 'MISLICE-ALEX', 'system');

INSERT INTO notifications (id, user_id, type, channel, title, body, read, created_by)
VALUES ('4bc78ced-538a-5018-becf-a1edac27bbdc', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'DEAL', 'PUSH', '🍕 2 Large Pizzas for $26', 'Shamz Pizza has a deal live near you — grab it while it''s hot.', FALSE, 'system');
INSERT INTO notifications (id, user_id, type, channel, title, body, read, created_by)
VALUES ('b51120d2-457b-56ef-8b86-790cec9a3299', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'REWARD', 'PUSH', 'You''re 260 points from Gold', 'Order this week to unlock free delivery perks.', FALSE, 'system');
INSERT INTO notifications (id, user_id, type, channel, title, body, read, created_by)
VALUES ('3690b02e-5319-5e63-aa2a-75aaa912f667', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'SYSTEM', 'PUSH', 'Welcome to MiSlice', 'Compare pizza prices across every shop in Michigan.', TRUE, 'system');

-- ── Demo orders with status history ─────────────────────────────────────────
INSERT INTO orders (id, order_number, user_id, restaurant_id, status, delivery_type, delivery_provider, delivery_address, subtotal, delivery_fee, provider_service_fee, platform_service_fee, tax, tip, discount, total, payment_method, payment_status, qr_token, estimated_eta_min, estimated_eta_max, placed_at, created_by)
VALUES ('0e6a5438-6b82-53b4-941e-7a275b3a051f', 'MS-100200', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', '00000000-0000-0000-0000-0000000000c1', 'DELIVERED', 'STORE_DELIVERY', 'store', '1234 Woodward Ave, Detroit, MI 48201', 18.77, 2.99, 0, 0, 1.13, 3.0, 0, 25.89, 'CASH_ON_DELIVERY', 'PAID', 'SHM7X2KP', 25, 35, '2026-06-10T19:22:00Z', 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('40ffdadc-5545-5637-bad2-669f686bfa41', '0e6a5438-6b82-53b4-941e-7a275b3a051f', 'Large Pepperoni Pizza', 1, 15.99, 15.99, 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('db855ced-3b3f-514b-8437-162f1b7682ca', '0e6a5438-6b82-53b4-941e-7a275b3a051f', 'Extra Cheese Add-on', 1, 1.49, 1.49, 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('6418e0a5-bdf9-5cd5-8ffa-bdbba4c8d626', '0e6a5438-6b82-53b4-941e-7a275b3a051f', 'Mushrooms Add-on', 1, 1.29, 1.29, 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('96ee97b2-f5ed-58bd-aeec-5f605c1afffd', '0e6a5438-6b82-53b4-941e-7a275b3a051f', NULL, 'PENDING', 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('e6966675-0e5d-5d4f-991e-8ebf6e14d204', '0e6a5438-6b82-53b4-941e-7a275b3a051f', 'PENDING', 'DELIVERED', 'system');
INSERT INTO loyalty_transactions (id, account_id, type, points, description, order_id) VALUES ('7673124b-a27e-5510-8bdd-6c6a228c6c41', '416ba529-3bc5-53cd-9076-c50476f1be81', 'EARN', 187, 'Order MS-100200', '0e6a5438-6b82-53b4-941e-7a275b3a051f');

INSERT INTO orders (id, order_number, user_id, restaurant_id, status, delivery_type, delivery_provider, delivery_address, subtotal, delivery_fee, provider_service_fee, platform_service_fee, tax, tip, discount, total, payment_method, payment_status, qr_token, estimated_eta_min, estimated_eta_max, placed_at, created_by)
VALUES ('b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', 'MS-100201', 'b89c84fa-81e5-5cdd-bd0f-97d70aa7d305', '1795704f-8414-5907-904c-9bb7b6c3c818', 'DELIVERED', 'STORE_DELIVERY', 'store', '502 E Liberty St, Ann Arbor, MI 48104', 25.56, 1.99, 0, 0, 1.53, 4.0, 0, 33.08, 'CASH_ON_DELIVERY', 'PAID', 'MCS4R9WQ', 25, 35, '2026-06-18T20:10:00Z', 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('cf3cbcbc-12da-535a-8f02-fbff17891ff8', 'b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', 'Medium BBQ Chicken Pizza', 2, 11.99, 23.98, 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('31ea1733-e45f-5b3c-897d-70d2ae943adb', 'b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', 'Cheddar Add-on', 1, 1.09, 1.09, 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('7f1a8e21-d8a0-5b41-9861-33b555a9caaa', 'b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', 'Ranch Drizzle', 1, 0.49, 0.49, 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('e6deca9d-fe55-5b4a-98da-c18fa3796162', 'b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', NULL, 'PENDING', 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('82c71c94-2158-5755-aaee-974677e33a12', 'b7d1ad9e-8d5c-56d0-a540-65c68bda7c0a', 'PENDING', 'DELIVERED', 'system');

INSERT INTO orders (id, order_number, user_id, restaurant_id, status, delivery_type, delivery_provider, delivery_address, subtotal, delivery_fee, provider_service_fee, platform_service_fee, tax, tip, discount, total, payment_method, payment_status, qr_token, estimated_eta_min, estimated_eta_max, placed_at, created_by)
VALUES ('d935a517-f83f-5c4b-8b05-000cb3f301ae', 'MS-100202', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'DELIVERED', 'STORE_DELIVERY', 'store', '1234 Woodward Ave, Detroit, MI 48201', 18.99, 2.49, 0, 0, 1.57, 0.0, 0, 25.04, 'CASH_ON_DELIVERY', 'PAID', 'ZMB1X9WP', 25, 35, '2026-06-15T18:30:00Z', 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('88005fb6-2dc6-59f8-ba52-1958960ef870', 'd935a517-f83f-5c4b-8b05-000cb3f301ae', 'Large Chicken Parmesan Pizza', 1, 18.99, 18.99, 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('e8f3153b-8b1c-5bf1-bfbe-9360942c521a', 'd935a517-f83f-5c4b-8b05-000cb3f301ae', NULL, 'PENDING', 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('8bbba13b-075a-5360-999c-43bbaa6efbf6', 'd935a517-f83f-5c4b-8b05-000cb3f301ae', 'PENDING', 'DELIVERED', 'system');
INSERT INTO loyalty_transactions (id, account_id, type, points, description, order_id) VALUES ('735677c5-01cc-5a81-ba9d-907cf4cdade9', '416ba529-3bc5-53cd-9076-c50476f1be81', 'EARN', 189, 'Order MS-100202', 'd935a517-f83f-5c4b-8b05-000cb3f301ae');

INSERT INTO orders (id, order_number, user_id, restaurant_id, status, delivery_type, delivery_provider, delivery_address, subtotal, delivery_fee, provider_service_fee, platform_service_fee, tax, tip, discount, total, payment_method, payment_status, qr_token, estimated_eta_min, estimated_eta_max, placed_at, created_by)
VALUES ('dbab1558-b581-526c-aae8-6692177863ed', 'MS-100203', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'DELIVERED', 'STORE_DELIVERY', 'store', '1234 Woodward Ave, Detroit, MI 48201', 15.99, 2.49, 0, 0, 1.32, 0.0, 0, 21.79, 'CASH_ON_DELIVERY', 'PAID', 'ZMB2X9WP', 25, 35, '2026-06-22T19:15:00Z', 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('930ed023-76f0-57e7-803f-90401bf44c91', 'dbab1558-b581-526c-aae8-6692177863ed', 'Medium Chicken Parmesan Pizza', 1, 15.99, 15.99, 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('2b1ae5b4-5e44-5bc8-b86e-4f6457b0a437', 'dbab1558-b581-526c-aae8-6692177863ed', NULL, 'PENDING', 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('de03f80e-75bf-52fb-971d-fdeba3147e15', 'dbab1558-b581-526c-aae8-6692177863ed', 'PENDING', 'DELIVERED', 'system');
INSERT INTO loyalty_transactions (id, account_id, type, points, description, order_id) VALUES ('bc2bfa4d-2a8a-59cb-b55d-ba64c26b8a92', '416ba529-3bc5-53cd-9076-c50476f1be81', 'EARN', 159, 'Order MS-100203', 'dbab1558-b581-526c-aae8-6692177863ed');

INSERT INTO orders (id, order_number, user_id, restaurant_id, status, delivery_type, delivery_provider, delivery_address, subtotal, delivery_fee, provider_service_fee, platform_service_fee, tax, tip, discount, total, payment_method, payment_status, qr_token, estimated_eta_min, estimated_eta_max, placed_at, created_by)
VALUES ('fd835e38-885f-5fa3-92cd-466995170221', 'MS-100204', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', 'ed958015-25f3-5f80-a4db-0fae863238ec', 'DELIVERED', 'STORE_DELIVERY', 'store', '1234 Woodward Ave, Detroit, MI 48201', 37.98, 2.49, 0, 0, 3.13, 0.0, 0, 45.59, 'CASH_ON_DELIVERY', 'PAID', 'ZMB3X9WP', 25, 35, '2026-06-29T20:00:00Z', 'system');
INSERT INTO order_items (id, order_id, item_name, quantity, unit_price, line_total, created_by) VALUES ('8dc18e07-6027-5d33-98bb-af285748f10c', 'fd835e38-885f-5fa3-92cd-466995170221', 'Large Chicken Parmesan Pizza', 2, 18.99, 37.98, 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('45454e17-0cad-55d7-ac89-1bb494ff8ed5', 'fd835e38-885f-5fa3-92cd-466995170221', NULL, 'PENDING', 'system');
INSERT INTO order_status_history (id, order_id, from_status, to_status, changed_by) VALUES ('1eaa3f77-3c38-5de7-8194-4fb9d9a029df', 'fd835e38-885f-5fa3-92cd-466995170221', 'PENDING', 'DELIVERED', 'system');
INSERT INTO loyalty_transactions (id, account_id, type, points, description, order_id) VALUES ('e405cd05-760d-5a22-bcd0-f3871064f65a', '416ba529-3bc5-53cd-9076-c50476f1be81', 'EARN', 379, 'Order MS-100204', 'fd835e38-885f-5fa3-92cd-466995170221');

-- ── Reviews on delivered demo orders ────────────────────────────────────────
INSERT INTO reviews (id, user_id, restaurant_id, order_id, rating, comment, moderation_status, created_by)
VALUES ('0c651efa-2b27-5f99-9305-8fad2a9b0dec', '52e3317e-96ba-5f9d-81fb-0794aa490bf4', '00000000-0000-0000-0000-0000000000c1', '0e6a5438-6b82-53b4-941e-7a275b3a051f', 5, 'Crispy edges, fast delivery — exactly what Detroit style should be.', 'APPROVED', 'system');

-- ── Price history samples ────────────────────────────────────────────────────
INSERT INTO price_history (id, restaurant_id, menu_item_id, price, source, captured_at) VALUES ('cb1e0cd0-a6fc-5da5-a0cd-41596fea55f2', '00000000-0000-0000-0000-0000000000c1', '6cda00a5-c3ca-531c-a66f-2c4c6444683a', 9.49, 'STORE_OWNER', now() - interval '30 days');
INSERT INTO price_history (id, restaurant_id, menu_item_id, price, source, captured_at) VALUES ('85c4824b-6f92-5f6f-bea0-dec138e8d114', '00000000-0000-0000-0000-0000000000c1', '6cda00a5-c3ca-531c-a66f-2c4c6444683a', 9.99, 'STORE_OWNER', now() - interval '7 days');

